AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Server S3

Resources:
  MinhasBuckets:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: "financeiro-caiocf"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Value: !GetAtt [MinhasBuckets, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [MinhasBuckets, DomainName]]]
    Description: Name of S3 bucket to hold website content